spring.application.name=MQJobv1
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Logging config
logging.file.name=C:/hdb/job_folder/logs/mqjob-application.log
logging.pattern.console=%d %-5level %logger : %msg%n
logging.pattern.file=%d %-5level [%thread] %logger : %msg%n

logging.level.root=ERROR
logging.level.com.fpt=INFO
logging.level.org.hibernate=ERROR

application.key.encrypt=SERCMjAyMQ==
application.mq-queue.host=10.15.119.83
application.mq-queue.port=1414
application.mq-queue.ccsid=1208
application.mq-queue.channel=GSO.GDT.SVR.CHAN
application.mq-queue.queue-manager=GSO.GDT.QMGR
application.mq-queue.queue-in=OUB.INBOX.INQ.QUEUE
application.mq-queue.queue-out=OUB.OUTBOX.INQ.QUEUE

scheduler.getMessageJob.fixedDelay=60000
scheduler.putMsgJob.fixedDelay=60000

app.datasource.jndi-name=java:comp/env/jdbc/dsTCS09
app.datasource.schema-name=TCS_HDB